version: '3.8'

services:
  api:
    build: ./api
    container_name: todo_api
    volumes:
      - ./api:/app
      - ./.data:/var/lib/app/data
      - ./.shared:/var/lib/app/shared
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379/0
    networks:
      - todo_network
    depends_on:
      - redis

  celery_worker:
    build: ./api
    container_name: todo_worker
    command: celery -A celery_app.celery worker --loglevel=info
    volumes:
      - ./api:/app
      - ./.data:/var/lib/app/data
      - ./.shared:/var/lib/app/shared
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379/0
    networks:
      - todo_network
    depends_on:
      - redis

  celery_beat:
    build: ./api
    container_name: todo_beat
    command: celery -A celery_app.celery beat --loglevel=info
    volumes:
      - ./api:/app
      - ./.data:/var/lib/app/data
      - ./.shared:/var/lib/app/shared
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379/0
    networks:
      - todo_network
    depends_on:
      - redis

  flower:
    build: ./api
    container_name: todo_flower
    command: celery -A celery_app.celery flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - REDIS_URL=redis://redis:6379/0
    networks:
      - todo_network
    depends_on:
      - redis
      - celery_worker

  redis:
    image: redis:alpine
    container_name: todo_redis
    networks:
      - todo_network

  nginx:
    build: ./nginx
    container_name: todo_nginx
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - todo_network

networks:
  todo_network:
    driver: bridge
